"""empty message

Revision ID: 627137e4f7d5
Revises: 24b84cb1ee03
Create Date: 2024-06-28 01:02:06.872568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627137e4f7d5'
down_revision = '24b84cb1ee03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_pending', sa.Boolean(), nullable=True))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('order_pending')

    # ### end Alembic commands ###
