"""empty message

Revision ID: 6f749ada027e
Revises: 627137e4f7d5
Create Date: 2024-06-28 01:05:03.731862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f749ada027e'
down_revision = '627137e4f7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('order_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('order_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
